---
engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - "**/*_test.go"
  - "**/mocks/*.go"
  - "asset/bindata.go"

