---

title: TODO
description: TODO
type: object
properties:
  type:
    description: TODO
    type: string
    enum:
      - build
  extends:
    description: TODO
    type: string
  dockerfile:
    description: TODO
    type: string
  tags:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  labels:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  arguments:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
additionalProperties: false
