---

definitions:
  stringOrList:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  fileList:
    type: object
    properties:
      files:
        $ref: '#/definitions/stringOrList'
      excludes:
        $ref: '#/definitions/stringOrList'
    additionalProperties: false

type: object
properties:
  extends:
    type: string
  ssh-identities:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  environment:
    type: array
    items:
      type: string
  registries:
    type: array
    items:
      type: object
  import:
    $ref: '#/definitions/fileList'
  export:
    $ref: '#/definitions/fileList'
  workspace:
    type: string
  tasks:
    type: object
  plans:
    type: object
  metaplans:
    type: object
additionalProperties: false
