---

title: TODO
description: TODO
type: object
properties:
  extends:
    description: TODO
    type: string
  ssh-identities:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  environment:
    description: TODO
    type: array
    items:
      type: string
  registries:
    description: TODO
    type: array
    items:
      description: TODO
      type: object
  import:
    description: TODO
    type: object
    properties:
      files:
        description: TODO
        oneOf:
          - type: string
          - type: array
            items:
              type: string
      excludes:
        description: TODO
        oneOf:
          - type: string
          - type: array
            items:
              type: string
    additionalProperties: false
  export:
    description: TODO
    type: object
    properties:
      files:
        description: TODO
        oneOf:
          - type: string
          - type: array
            items:
              type: string
      excludes:
        description: TODO
        oneOf:
          - type: string
          - type: array
            items:
              type: string
    additionalProperties: false
  workspace:
    description: TODO
    type: string
  tasks:
    description: TODO
    type: object
  plans:
    description: TODO
    type: object
  metaplans:
    description: TODO
    type: object
additionalProperties: false
