---

definitions:
  stringOrList:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  fileList:
    type: object
    properties:
      files:
        $ref: '#/definitions/stringOrList'
      excludes:
        $ref: '#/definitions/stringOrList'
    additionalProperties: false

type: object
properties:
  extends:
    type: string
  options:
    type: object
    properties:
      force-sequential:
        type: boolean
      healthcheck-interval:
        type: string
      ssh-identities:
        oneOf:
          - type: string
          - type: array
            items:
              type: string
    additionalProperties: false
  registries:
    type: array
    items:
      type: object
  workspace:
    type: string
  environment:
    $ref: '#/definitions/stringOrList'
  import:
    $ref: '#/definitions/fileList'
  export:
    $ref: '#/definitions/fileList'
  tasks:
    type: object
  plans:
    type: object
  metaplans:
    type: object
additionalProperties: false
