---

definitions:
  environment:
    description: TODO
    type: array
    items:
      type: string

  task:
    description: TODO
    type: object
    properties:
      extends:
        description: TODO
        type: string
      image:
        description: TODO
        type: string
      command:
        description: TODO
        type: string
      shell:
        description: TODO
        type: string
      script:
        description: TODO
        type: string
      entrypoint:
        description: TODO
        type: string
      hostname:
        description: TODO
        type: string
      detach:
        description: TODO
        type: boolean
      healthcheck:
        $ref: '#/definitions/healthcheck'
      environment:
        $ref: '#/definitions/environment'
      required_environment:
        description: TODO
        type: array
        items:
          type: string
    additionalProperties: false

  healthcheck:
    description: TODO
    type: object
    properties:
      command:
        description: TODO
        type: string
      interval:
        description: TODO
        type: string
      retries:
        description: TODO
        type: integer
      start_period:
        description: TODO
        type: string
      timeout:
        description: TODO
        type: string
    additionalProperties: false

  plan:
    description: TODO
    type: object
    properties:
      stages:
        description: TODO
        type: array
        items:
          $ref: '#/definitions/stage'
      environment:
        $ref: '#/definitions/environment'
    additionalProperties: false

  stage:
    description: TODO
    type: object
    properties:
      name:
        description: TODO
        type: string
      tasks:
        description: TODO
        type: array
        items:
          $ref: '#/definitions/stage_task'
      concurrent:
        description: TODO
        type: boolean
      environment:
        $ref: '#/definitions/environment'
    additionalProperties: false
    required:
      - name

  stage_task:
    description: TODO
    oneOf:
      - type: string
      - type: object
        properties:
          name:
            description: TODO
            type: string
          environment:
            $ref: '#/definitions/environment'
        additionalProperties: false
        required:
          - name

type: object
properties:
  extends:
    type: string
    minLength: 1
  environment:
    $ref: '#/definitions/environment'
  import:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  export:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  exclude:
    description: TODO
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  tasks:
    description: TODO
    type: object
    additionalProperties:
      $ref: '#/definitions/task'
  plans:
    description: TODO
    type: object
    additionalProperties:
      $ref: '#/definitions/plan'
additionalProperties: false
