---

definitions:
  environment:
    description: TODO
    type: array
    items:
      type: string

  task:
    description: TODO
    type: object
    properties:
      image:
        description: TODO
        type: string
      command:
        description: TODO
        type: string
      shell:
        description: TODO
        type: string
      script:
        description: TODO
        type: string
      environment:
        $ref: '#/definitions/environment'
      required_environment:
        description: TODO
        type: array
        items:
          type: string
    additionalProperties: false
    required:
      - image

  plan:
    description: TODO
    type: object
    properties:
      stages:
        description: TODO
        type: array
        items:
          $ref: '#/definitions/stage'
      environment:
        $ref: '#/definitions/environment'
    additionalProperties: false

  stage:
    description: TODO
    type: object
    properties:
      name:
        description: TODO
        type: string
      tasks:
        description: TODO
        type: array
        items:
          $ref: '#/definitions/stage_task'
      concurrent:
        description: TODO
        type: boolean
      environment:
        $ref: '#/definitions/environment'
    additionalProperties: false
    required:
      - name

  stage_task:
    description: TODO
    type: object
    properties:
      name:
        description: TODO
        type: string
      environment:
        $ref: '#/definitions/environment'
    additionalProperties: false
    required:
      - name

type: object
properties:
  environment:
    $ref: '#/definitions/environment'
  tasks:
    description: TODO
    type: object
    additionalProperties:
      $ref: '#/definitions/task'
  plans:
    description: TODO
    type: object
    additionalProperties:
      $ref: '#/definitions/plan'
additionalProperties: false
